### ISSUE TITLE
SDK client initialization throws error

### ISSUE THREAD

**Issue by gsheppard** [launchdarkly/js-core#118]
**Describe the bug**

When initializing the client, I get `TypeError: Native module not found: ../package.json`. I believe it's because of [this file](https://github.com/launchdarkly/js-core/blob/40c5d51e8940bd6e24222985bd6c3a41afe3ee49/packages/sdk/vercel/src/createPlatformInfo.ts#L3), which has a different relative location to the `package.json` when compiled to CJS+ESM.

**To reproduce**

```js
import LaunchDarkly from '@launchdarkly/vercel-server-sdk'
import { createClient } from '@vercel/edge-config'

export const config = {
  matcher: '/((?!api|static|.*\\..*|_next|_vercel).*)',
}

export async function middleware() {
  const edgeClient = createClient(process.env.EDGE_CONFIG)
  const ldClient = LaunchDarkly.init('sdk-8e0b47f2-9422-43b0-969b-e36583872175', edgeClient)

  return NextResponse.next()
}
```

**Expected behavior**
That the client would not throw an error.

**SDK version**
```
"@launchdarkly/vercel-server-sdk": "^0.2.2",
"@vercel/edge-config": "^0.1.10",
```

**Language version, developer tools**
- Next 13.4.2
- Node 16.17.0
- Turborepo 1.4.2

**Comment by kinyoklion** [comment]
Hello @gsheppard,

Thank you for reporting this issue. It should be fixed in 0.3.0.

Thanks,
Ryan
