### ISSUE TITLE
Integration testData package is not working as expected

### ISSUE THREAD

**Issue by husseinsakr** [launchdarkly/js-core#192]
**Describe the bug**

It appears that updating [TestData](https://launchdarkly.github.io/js-core/packages/sdk/server-node/docs/classes/integrations.TestData.html) mock store through [TestDataFlagBuilder](https://launchdarkly.github.io/js-core/packages/sdk/server-node/docs/classes/integrations.TestDataFlagBuilder.html) is not working as expected. This issue was observed after upgrading to the new package `@launchdarkly/node-server-sdk` from `launchdarkly-node-server-sdk`.

**To reproduce**
Here is the test case that broke.

```js

const flagKey = 'test-flag-1'
const tenantId = 'abcd'.repeat(8)
const launchDarklyUri = 'http://test-launchdarkly'
const launchDarklyStreamUri = `${launchDarklyUri}/relay`
const region = 'local'

const testData = new TestData()
const ldClient = LaunchDarklyClient.init(launchDarklySdkKey, {
        updateProcessor: testData.getFactory(),
        streamUri: launchDarklyStreamUri,
        baseUri: 'OVERRIDE_DEFAULT',
        eventsUri: 'OVERRIDE_DEFAULT',
        sendEvents: false,
        diagnosticOptOut: true,
        allAttributesPrivate: true
})

// Connect client
await ldClient.waitForInitialization()

// Create a boolean flag
await testData.update(testData.flag(flagKey).booleanFlag().variationForAll(true))

// Add a tenantId rule
await testData.update(testData.flag(flagKey)
        .ifMatch('user', 'tenantId', tenantId)
        .thenReturn(false))

// Evaluate with no tenantId
const flagsState = await ldClient.allFlagsState({
        kind: 'user',
        key: 'Global',
        tenantId: undefined,
        region
})

// Result is { 'test-flag-1': null }
const features = flagsState.allValues()

// Fails here
assert.isTrue(features[flagKey])

// Evaluate with tenantId
const flagsStateWithTenant = await ldClient.allFlagsState({
        kind: 'user',
        key: tenantId,
        tenantId,
        region
})

// Result is { 'test-flag-1': false }
const featuresWithTenant = flagsStateWithTenant.allValues()

// Works as expected here
assert.isFalse(featuresWithTenant[flagKey])
```

**Expected behavior**
Evaluation with no tenantId in context should have returned `true` for the flag. 

**Logs**
N/A

**SDK version**

8.0.1

**Language version, developer tools**
Node v16.18.1

**OS/platform**
Mac M1

**Additional context**
This test case worked in previous package latest version

**Comment by kinyoklion** [comment]
@husseinsakr,

Thank you for the report. We will look into this. I really appreciate the reproduction case.

__Filed internally as 208611__

Thank you,
Ryan

**Comment by kinyoklion** [comment]
Hello @husseinsakr,

This is fixed in 8.0.2. Thank you for the report! Let me know if things are working for you now.

**Comment by husseinsakr** [comment]
Thank you @kinyoklion ! I will verify shortly and get back to you.

Cheers

**Comment by husseinsakr** [comment]
Issue resolved ✅ . Thank you!
