### ISSUE TITLE
allFlagsState in the new package is 10x slower than launchdarkly-node-server-sdk@7.0.2

### ISSUE THREAD

**Issue by randing89** [launchdarkly/js-core#229]
**Describe the bug**
`allFlagsState` is 10x slower in `@launchdarkly/node-server-sdk@8.1.1` than `launchdarkly-node-server-sdk@7.0.2`.

**To reproduce**
Run following script with both package
```
// const ld = require("launchdarkly-node-server-sdk");
const ld = require("@launchdarkly/node-server-sdk");

const user = {
  key: "abc",
};

async function fetchFlags() {
  const client = ld.init("{sdk_key}");
  client.once("ready", async () => {
    while (true) {
      const start = performance.now();
      await client.allFlagsState(user);
      console.log(performance.now() - start);
    }
  });
}

fetchFlags();

```

**Expected behavior**
Performance does not slow down

**Logs**
First result is running with `launchdarkly-node-server-sdk@7.0.2`
<img width="915" alt="image" src="https://github.com/launchdarkly/js-core/assets/640557/4a795298-7311-453f-8b3e-d5975850a265">

**Language version, developer tools**
Same result in Node 16 & 18

**Comment by kinyoklion** [comment]
Hello @randing89,

We will take a look into this. Do you know how many flags are in your environment? Do you also have a support ticket open if I need to collect information?

Thank you,
Ryan

_Filed internally as 212440_

**Comment by kinyoklion** [comment]
Hello @randing89,

From local testing it would seem that the majority of this slowdown was from an issue with how we were compiling our typescript.

We were targeting `es6` instead of `es2017` or newer. This was causing the typescript compiler to effectively polyfill async/await. The way it polyfills them uses generators and was causing a substantial performance impact.

I've release `8.2.0-beta.1` and would appreciate your feedback about how it handles your configuration.

 This does not 100% close the performance gap. I will continue to investigate, especially for the cases where you have many outstanding allFlagsState evaluations.

Thank you,
Ryan

**Comment by kinyoklion** [comment]
The 8.1.2 release now includes this change. I will look at some additional performance changes as well.

It would still be helpful for you to include your environment information in the zendesk support ticket so we can target any performance problems unique to this payload as well.

**Comment by randing89** [comment]
@kinyoklion Thanks for looking into it. I can confirm the single request has gone down from 700ms to 150ms when testing from my machine. It still has some gap when comparing to 7.0.2 (70ms) and 6.4.3 (< 10ms)

Running the same test code with 6.4.3 from my machine
<img width="716" alt="image" src="https://github.com/launchdarkly/js-core/assets/640557/4e0468ab-a699-4551-9777-b117d71ac1e0">

**Comment by kinyoklion** [comment]
Is it ok if we evaluate flags using your environment for testing? I suspect your payload is hitting some specific path that is less than optimal. For both v7 and 8. 

v7 added context support. So if you went to a version before that, and you are using contexts, then there would just be things that are not getting evaluated.

Aside from that the only real overhead for v7 versus 6 would be additional checking for recursive situations enabled by nested segment support.

Thank you,
Ryan

**Comment by randing89** [comment]
Hi,Sure go ahead. Thanks.Regards,RanOn 11 Aug 2023, at 08:26, Ryan Lamb ***@***.***> wrote:﻿
Is it ok if we evaluate flags using your environment for testing? I suspect your payload is hitting some specific path that is less than optimal. For both v7 and 8.
v7 added context support. So if you went to a version before that, and you are using contexts, then there would just be things that are not getting evaluated.
Aside from that the only real overhead for v7 versus 6 would be additional checking for recursive situations enabled by nested segment support.
Thank you,
Ryan

**Comment by randing89** [comment]
Fixed as part of https://github.com/launchdarkly/js-core/issues/230
