### ISSUE TITLE
allFlagsState does not retrieve flags configured to be client-side available when using a FileDataSource

### ISSUE THREAD

**Issue by guilherme-barcelos-xero** [launchdarkly/js-core#269]
**Describe the bug**
`allFlagsState` does not retrieve [flags configured to be client-side available](https://github.com/guilherme-barcelos-xero/ld-node-client-side-flags-bug/blob/b2d3809b15bfb5f58e6c372a1e8f07ce56e416f6/local-flags.json#L4-L6) (`clientSideOnly` prop) when using a `FileDataSource`.

**To reproduce**
Run [index.js](https://github.com/guilherme-barcelos-xero/ld-node-client-side-flags-bug/blob/main/index.js) from [repo](https://github.com/guilherme-barcelos-xero/ld-node-client-side-flags-bug) that logs to the console different results.
`client.allFlagsState(user)` response contains `test-flag`, whereas `client.allFlagsState(user, { clientSideOnly: true })` is empty.

**Expected behavior**
Call to `allFlagsState` with `{ clientSideOnly: true }` returns the flags configured as client-side available in JSON file.

**Logs**
![image](https://github.com/launchdarkly/js-core/assets/97889880/9c8bbd10-ef24-47fe-80b1-69e8f293fdd3)

**SDK version**
7.0.1

**Language version, developer tools**
Node 18

**Comment by kinyoklion** [comment]
Hello @guilherme-barcelos-xero,

Thank you for the issue. You should be able to work around this by putting `"clientSide": true` in the flag. The back end would provide both pieces of information (clientSideAvailability and the older clientSide).

I'll also get a fix in place.

_Filed internally as 216040_

Thank you,
Ryan

**Comment by guilherme-barcelos-xero** [comment]
Hey @kinyoklion ,

Adding `"clientSide": true` to the flag worked.

Thanks!
Guilherme
