### ISSUE TITLE
Typesafe API for TypeScript consumers

### ISSUE THREAD

**Issue by josephearl** [launchdarkly/js-core#285]
**Is your feature request related to a problem? Please describe.**

An API for TypeScript users to retrieve toggle values in a typesafe manner.

**Describe the solution you'd like**

Similar to the Java SDK, provide methods like `boolVariation` and `stringVariation` on `LDClient` for TypeScript users that only accept a default value of the correct type, and throw an error if the resolved value from LaunchDarkly is not of the correct type.

**Comment by kinyoklion** [comment]
Hey @josephearl,

Thank you for the request, I think that adding type safe methods would be reasonable.

They would though, behave like they do in other SDKs. We try never to throw or do unexpected things in methods that are called after an applications initialization.

The behavior instead is to use the default value. If the detailed methods are used, then we include details in the indication, which would include an error kind of `WRONG_TYPE`.

We could also consider generics.

_Filed internally as 218820_

Thank you,
Ryan

**Comment by kinyoklion** [comment]
@josephearl I've published a pre-release `9.0.0-alpha.5` which contains these methods if you want to give them a try.

We are working on some other features and 9.0.0 will be released when those are ready.

Thank you,
Ryan

**Comment by josephearl** [comment]
@kinyoklion thanks will take a look

**Comment by kinyoklion** [comment]
9.0.0 has been released and includes typed variation methods.

Thank you,
Ryam
