### ISSUE TITLE
Use `unknown` instead of `any`

### ISSUE THREAD

**Issue by josephearl** [launchdarkly/js-core#286]
**Is your feature request related to a problem? Please describe.**

Now the SDK has been converted to TypeScript, it should not use `any` anymore.

Use of `any` causes problems for library consumers that use TypeScript in strict mode, as well as errors from the recommended set of TypeScript ESLint rules like https://typescript-eslint.io/rules/no-explicit-any/.

`any` is an escape hatch that disables type checking and allows you to access arbitrary properties, even ones that don’t exist.

**Describe the solution you'd like**

Use `unknown` instead of `any`. This would be a breaking change so would require a major version bump following SemVer.

**Comment by kinyoklion** [comment]
Hello @josephearl,

I have responded to your other issue, which I think largely covers type safe cases.

I am not going to change the return type for the variation method though. 

What we could consider is an additional method, such as `jsonVariation`, method which uses unknown. 

Thank you,
Ryan

**Comment by josephearl** [comment]
Thanks, I guess we can close this issue then
