### ISSUE TITLE
No matching version found for semver@7.5.4 

### ISSUE THREAD

**Issue by Jaspalao** [launchdarkly/js-core#307]
**Is this a support request?**
This issue tracker is maintained by LaunchDarkly SDK developers and is intended for feedback on the code in this library. If you're not sure whether the problem you are having is specifically related to this library, or to the LaunchDarkly service overall, it may be more appropriate to contact the LaunchDarkly support team; they can help to investigate the problem and will consult the SDK team if necessary. You can submit a support request by going [here](https://support.launchdarkly.com/) and clicking "submit a request", or by emailing support@launchdarkly.com.

Note that issues filed on this issue tracker are publicly accessible. Do not provide any private account information on your issues. If your problem is specific to your account, you should submit a support request as described above.

**Describe the bug**
When running npm i with our project the  the error No matching version found for semver@7.5.4 whcih then stops installing all other packages.

**To reproduce**
Steps to reproduce the behavior.
install "@launchdarkly/node-server-sdk": "^8.2.3", to a package that is deployed to aws.
I cloned an existing repo, ran npm i and receieved the error 

**Expected behavior**
If you have multiple packages in the packages.json file, they will not be installed

**Logs**
If applicable, add any log output related to your problem.
Log output:
verbose stack semver: No matching version found for semver@7.5.4.
20749 verbose Windows_NT 10.0.19045
20750 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i"
20751 verbose node v14.21.3
20752 verbose npm  v6.14.18
20753 error code ETARGET
20754 error notarget No matching version found for semver@7.5.4.
20755 error notarget In most cases you or one of your dependencies are requesting
20755 error notarget a package version that doesn't exist.
20755 error notarget
20755 error notarget It was specified as a dependency of '@launchdarkly/js-server-sdk-common'
20756 verbose exit [ 1, true ]

**SDK version**
The version of this SDK that you are using.
"@launchdarkly/node-server-sdk": "^8.2.3"
**Language version, developer tools**
For instance, Go 1.11 or Ruby 2.5.3. If you are using a language that requires a separate compiler, such as C, please include the name and version of the compiler too.

**OS/platform**
For instance, Ubuntu 16.04, Windows 10, or Android 4.0.3. If your code is running in a browser, please also include the browser type and version.
 Windows_NT 10.0.19045
**Additional context**

**Comment by kinyoklion** [comment]
Hey @Jaspalao,

The `semver` package at `7.5.4` does exist It does exist and installs fine today.

It is not a satisfying answer, but my initial suggestion would be to try again in case you encountered some intermittent issue with npmjs.

If it doesn't work, then you could make an empty project and see if you can install `semver@7.5.4`. If not, then it could give you a minimal configuration to help track down network or npm configuration problems.

Unfortunately npm will produce messages like this even though the underlying cause if often some temporary network condition.

Thank you,
Ryan
