### ISSUE TITLE
`waitForInitialization()` returns a internal `LDClient` type than the type returned from `init()`

### ISSUE THREAD

**Issue by Velitheda** [launchdarkly/js-core#324]
**Describe the bug**

`waitForInitialization` is returning an internal `LDClient` type, instead of the `LDClient` that is exported, causing TypeScript compile errors if I want to use the output from the function.

**To reproduce**

```
import { init } from '@launchdarkly/node-server-sdk'
import type { LDClient } from '@launchdarkly/node-server-sdk'
import type { LDClient as LDClientCommon } from '@launchdarkly/js-server-sdk-common'

const ldClient: LDClient = init('sdk-key', {})

// Should be LDClient:
const initializedClient: LDClientCommon = await ldClient.waitForInitialization()
```

**Expected behavior**

`waitForInitialization` should return the `LDClient` type from `node-server-sdk`, not `js-server-sdk-common`

**SDK version**
`v9.0.4`

**Language version, developer tools**
Typescritp `v4.9.5` on Node `v18.16.0`

**OS/platform**
macOS Ventura Version `13.5.2`

**Additional context**
I can currently get around the issue by doing the following:

```
const ldClient: LDClient = init('sdk-key', {})

await ldClient.waitForInitialization()

if (!ldClient.initialized()) {
    logger.error('LaunchDarkly client failed to initialize')
}

return ldClient
```

**Comment by keanan** [comment]
Hello @kinyoklion,

We are facing a similar issue where trying to add inspectors as per the [docs](https://docs.launchdarkly.com/sdk/features/inspectors/?q=inspector) but getting errors from the client which is returned. 

The type declarations are correctly [added](https://github.com/launchdarkly/js-core/blob/main/packages/shared/sdk-client/src/api/LDOptions.ts) but this is not what is being returned. 

Should we ignore the TS error and use the following?
```
const client = ld.init("SDK-KEY", {
      logger: log,
      inspectors: [
        {
          type: 'flag-used',
          name: 'inspector',
         ...
        },
      ],
    });
```
Thanks
