### ISSUE TITLE
Bug on building package with @launchdarkly/node-server-sdk as dependency

### ISSUE THREAD

**Issue by enniogonzalez** [launchdarkly/js-core#347]
Hey guys, 

I have a library that i built with the library launchdarkly-node-server-sdk 6.2.0, and i'm trying to migrate to @launchdarkly/node-server-sdk 9.0.5, but i'm facing an issue when packing my library, the compiler throws this error

![image](https://github.com/launchdarkly/js-core/assets/19171556/cc598b03-f4ae-4c5c-aa83-874460c28ab2)

**Logs**
```
> tsc

node_modules/@launchdarkly/js-sdk-common/dist/internal/stream/index.d.ts:2:15 - error TS1005: ',' expected.

2 import { type StreamingErrorHandler } from './types';
                ~~~~~~~~~~~~~~~~~~~~~

node_modules/@launchdarkly/js-sdk-common/dist/internal/stream/index.d.ts:3:35 - error TS1005: ',' expected.

3 export { StreamingProcessor, type StreamingErrorHandler };
                                    ~~~~~~~~~~~~~~~~~~~~~



Found 2 errors.
```
**SDK version**
9.0.5

**OS/platform**
Windows 11

**Comment by ismaelgt** [comment]
This is the same issue I've reported here: https://github.com/launchdarkly/js-core/issues/345 and there's a merge request to fix it: https://github.com/launchdarkly/js-core/pull/346.

Hopefully we'll get this merged soon 🙂

**Comment by ismaelgt** [comment]
This issue should now be fixed in https://github.com/launchdarkly/js-core/releases/tag/node-server-sdk-v9.0.6

**Comment by kinyoklion** [comment]
@enniogonzalez I am going to close this issue. Let me know if you still encounter any problem.

Thanks @ismaelgt!
