### ISSUE TITLE
Update @vercel/edge-config dependency

### ISSUE THREAD

**Issue by gmerwan** [launchdarkly/js-core#379]
**Is your feature request related to a problem? Please describe.**

No problem in particular, but it would be great to have the dependency `@vercel/edge-config` being updated to latest version as it has some breaking changes causing a type issue with `init` argument

**Describe the solution you'd like**

Update `@vercel/edge-config dependency` to v1 🙏🏻

**Comment by yusinto** [comment]
Thank you for submitting this issue. We are looking at this internally and will provide an update soon. Internally logged as #235330.

**Comment by yusinto** [comment]
We have corrected the code samples in the [Vue SDK Docs ](https://docs.launchdarkly.com/sdk/client-side/vue#retrieving-flag-values-with-the-client)as per your report. Thank you for letting us know!

**Comment by yusinto** [comment]
This will be fixed in the next minor release #393 .
