### ISSUE TITLE
Launchdarkly useBoolVariation not working in android: {"reason": {"errorKind": "USER_NOT_SPECIFIED", "kind": "ERROR"}, "value": false, "variationIndex": null}

### ISSUE THREAD

**Issue by vl-kumar** [launchdarkly/js-core#421]
**Describe the bug**
I am using Launchdarkly version 10.0.0. While I am trying to get boolean value via useBoolVariation from Launchdarkly but is working only in iOS. For android I am always getting false value
In Android useBoolVariation not working to check the full details I used useBoolVariationDetail it's returning this error
{"reason": {"errorKind": "USER_NOT_SPECIFIED", "kind": "ERROR"}, "value": false, "variationIndex": null}

**Expected behavior**
useBoolVariation has to return correct value what we configured in launchdarkly in android and ios.

**SDK version**
 10.0.0

**Language version, developer tools**
React Native - 0.72.6

**OS/platform**
Android

**Comment by yusinto** [comment]
It sounds like the ldContext is not set when `useBoolVariationDetail` is called. Please check:

* Make sure you call identify with a valid context before using any of the variation hooks.
* Make sure you await that identify call.

If those does not help, please follow these steps so we can investigate this further:

* Please try running the [example app](https://github.com/launchdarkly/js-core/blob/main/packages/sdk/react-native/example/App.tsx#L12) and ensure you can run that correctly.
* Please turn debug on and post the logs. See the [example app](https://github.com/launchdarkly/js-core/blob/main/packages/sdk/react-native/example/App.tsx#L12) on how to do this.
* Please supply the code demonstrating the client initialization and provider usage, as well as the identify and variation calls.
