### ISSUE TITLE
Does react-native-client-sdk (v10) support expo web?

### ISSUE THREAD

**Issue by QuanGao-osmind** [launchdarkly/js-core#455]
**Describe the bug**
We have an expo project that we are targeting both mobile and web platforms. The react-native-client-sdk works well on mobile but crashes in web.

This is the error I see:
```
autoEnv.js:24 Uncaught TypeError: Cannot read properties of undefined (reading 'Manufacturer')
```
which traces to this code in `autoEnv`, looks like `Platform.constants` is `undefined`.
```
export const ldDevice = {
    // key is populated by common/client-sdk
    key: '',
    envAttributesVersion: '1.0',
    manufacturer: Platform.select({
        ios: 'apple',
        android: Platform.constants.Manufacturer,
    }),
    model: Platform.select({
        // ios: model n/a from PlatformIOSStatic
        android: Platform.constants.Model,
    }),
    os: {
        family: Platform.select({
            ios: 'apple',
            default: Platform.OS,
        }),
        name: Platform.OS,
        version: (_a = Platform.Version) === null || _a === void 0 ? void 0 : _a.toString(),
    },
};
```

**To reproduce**
Follow the SDK doc to initialize LD client and identify user.

**Expected behavior**
Expect `react-native-client-sdk` to work on all platforms expo support (Android, IOS, web)

**SDK version**
`10.1.3`

**OS/platform**
Web browser: Chrome Version 124.0.6367.62

Any insights are greatly appreciated, thank you!

**Comment by QuanGao-osmind** [comment]
@louis-launchdarkly Thank you for the reply!

We are able to apply a patch to the package to get around the issue in `autoEnv`. 

Do you have any suggestions in getting around the CORS issue?

**Comment by yusinto** [comment]
@QuanGao-osmind the react-native SDK is designed, built and tested for iOS and Android only. Other platforms are not supported. Web is not supported. The cors issue is due to http requests made to the LaunchDarkly mobile endpoints from a browser. We use different endpoints for these platforms and these are also coupled tightly with the use of mobile keys and client side ids.

**Comment by louis-launchdarkly** [comment]
Based on the investigation so far, while we have the feature request captured in the internal ticket I mentioned above, currently there is no ETA of when our RN SDK can support expo web. Trying to use the Client ID and the endpoints for the browser could be a thing to try.

**Comment by QuanGao-osmind** [comment]
@louis-launchdarkly @yusinto Thank you for the updates!

I thought react-native SDK is fully compatible with Expo because of the documentation [here](https://docs.launchdarkly.com/sdk/client-side/react/react-native)
<img width="562" alt="Screenshot 2024-05-10 at 8 45 59 AM" src="https://github.com/launchdarkly/js-core/assets/156127899/dff577da-9696-4c4b-9c7c-be47b0a401aa">

If there's no immediate plan to support Expo web, could LD team update this documentation to reflect that? 

FWIW we tested LD in Expo web in a security-disabled browser and it seems to work fine (with a patch to fix the above issue). It could be very close to get LD fully compatible with all platforms Expo support.

**Comment by QuanGao-osmind** [comment]
@yusinto @louis-launchdarkly Followup question, which SDK would you recommend us to use for Expo web?

In the [documentation](https://docs.launchdarkly.com/sdk/client-side/react/react-web) for `React Web SDK`, I see 
```
The React Web SDK does not work in React Native projects
If you want to add LaunchDarkly to your React Native codebase, use the React Native SDK instead.
```

Do we need to resort to `JavaScript SDK`?

**Comment by retronouns** [comment]
My team just ran into this issue as well! ❤️ 

It's very useful to be able to run our apps in web mode during local development, so I am happy to see there is a ticket to address it, even if there is no ETA yet. 😄

**Comment by retronouns** [comment]
@QuanGao-osmind We ended up needing to use both the RN SDK and the JS SDK and have 2 implementations: `abcd.tsx` that uses the RN SDK, and `abcd.web.tsx` that uses the JS SDK.

**Comment by QuanGao-osmind** [comment]
@retronouns Thank you for the update! We ended up using a similar approach, except we used RN SDK and React web SDK.
