### ISSUE TITLE
[LaunchDarklyTimeoutError: identify timed out after 5 seconds.]

### ISSUE THREAD

**Issue by samtags** [launchdarkly/js-core#457]
**Describe the bug**
LaunchDarklyTimeoutError log is showing when running the app in Android and not getting the correct variation value. 

**To reproduce**
Render this component at the top level of your app.
Run the app in Android device and you will see the error. 
```
import {
  LDProvider,
  ReactNativeLDClient,
  AutoEnvAttributes,
} from "@launchdarkly/react-native-client-sdk";
import { useEffect } from "react";

const ctx = {
  kind: "user",
  key: "anonymous-key",
  debug: true,
};

const client = new ReactNativeLDClient(
  "PROJECT_KEY",
  AutoEnvAttributes.Disabled
);

const LaunchdarklyProvider = ({ children }) => {
  useEffect(() => {
    client.identify(ctx).catch((e) => console.log(e));
  }, []);

  return <LDProvider client={client}>{children}</LDProvider>;
};

export default LaunchdarklyProvider;
```

**Expected behavior**
The error should not show and should be able to get the correct variation value. 

**Logs**
 LOG  error: [LaunchDarkly] identify error: LaunchDarklyTimeoutError: identify timed out after 5 seconds.
 LOG  [LaunchDarklyTimeoutError: identify timed out after 5 seconds.]

**SDK version**
"@launchdarkly/react-native-client-sdk": "10.1.1"

**Language version, developer tools**
"react-native": "0.73.6"
"expo": "~50.0.17"

**OS/platform**
- Mac OS Sonoma 14.4.1 
- Any Android Emulator

**Additional context**
Works fine in iOS issue only occurs in Android.

**Comment by patrickcbrady** [comment]
> ➕1 We are seeing the same error in our Android simulators and physical devices.

sdk version: 10.1.3
react-native: 0.72.10
expo: 49.0.23

**Comment by samtags** [comment]
Issue was resolved when flipper is removed from build.gradle and Mainapplication.kt. I found it [here](https://github.com/launchdarkly/js-core/issues/375#issuecomment-1945529737).

**Comment by MDG-JHowley** [comment]
If you can't figure out what is messing with the streaming network requests another option would be to switch to the polling connection mode i.e.

```javascript
const ldClient = new ReactNativeLDClient(...);
ldClient.setConnectionMode('polling');
```
