### ISSUE TITLE
Memory Leak Inside LruCache

### ISSUE THREAD

**Issue by eholland-banno** [launchdarkly/js-core#474]
**Describe the bug**
It appears that the [keyMap](https://github.com/launchdarkly/js-core/blob/8ff641be8b32f24884457bd506566e283cf04e40/packages/shared/sdk-server/src/cache/LruCache.ts#L29) used to store indexes for retrieving [values](https://github.com/launchdarkly/js-core/blob/8ff641be8b32f24884457bd506566e283cf04e40/packages/shared/sdk-server/src/cache/LruCache.ts#L19) is a memory leak. When [clear()](https://github.com/launchdarkly/js-core/blob/8ff641be8b32f24884457bd506566e283cf04e40/packages/shared/sdk-server/src/cache/LruCache.ts#L105-L113) runs on the cache, it clears out _most_ of the data stored except for the `keyMap` which can grow infinitely as [unique keys get added into the cache](https://github.com/launchdarkly/js-core/blob/8ff641be8b32f24884457bd506566e283cf04e40/packages/shared/sdk-server/src/cache/LruCache.ts#L68). It also seems like the indexes stored in the `keyMap` would become stale on `clear()` since they would no longer point to the correct index in the `values` array.

**To reproduce**
If you call `client.variation(key, context, defaultValue)` many times passing unique keys, the `keyMap` will continue to grow infinitely even if `clear()` were to be called.

**Expected behavior**
I would expect a call to `this.keyMap.clear()` in the [LruCache's clear()](https://github.com/launchdarkly/js-core/blob/8ff641be8b32f24884457bd506566e283cf04e40/packages/shared/sdk-server/src/cache/LruCache.ts#L105-L113) function like so:
```js
  clear() {
    ...
    this.keyMap.clear();
  }
```
Local testing of this has proven to reduce the memory as we're clearing out the `keyMap` periodically.

**SDK version**
@launchdarkly/js-server-sdk-common version 1.2.3

**Language version, developer tools**
Node 18.19.0

**OS/platform**
macOS 14.4

**Comment by kinyoklion** [comment]
Thank you for the report and details @eholland-banno 

We will take a look.

_Filed internally as 246138_

**Comment by kinyoklion** [comment]
@eholland-banno The fix has been released in 9.4.4.

**Comment by eholland-banno** [comment]
> @eholland-banno The fix has been released in server common 2.4.2 (Node server 9.4.4). Let me know if you have any challenges with version upgrades.

Awesome, will do. Thanks a ton for the fast response @kinyoklion!
