### ISSUE TITLE
Inspector Support

### ISSUE THREAD

**Issue by lolJS** [launchdarkly/js-core#497]
**Is your feature request related to a problem? Please describe.**
I would love to see the react-native SDK support inspectors or provide a similar event:

```js
 inspectors: [
    {
      type: "flag-used",
      name: "dd-inspector",
      method: (key: string, detail: LDClient.LDEvaluationDetail) => {
        datadogRum.addFeatureFlagEvaluation(key, detail.value);
      },
    },
  ],
```

**Describe the solution you'd like**
Inspector support: https://docs.launchdarkly.com/sdk/features/inspectors#javascript

**Describe alternatives you've considered**
I explored using the SDK's existing `client.on("change")` event.

**Comment by sergioalmela** [comment]
Same for node

**Comment by kinyoklion** [comment]
Hello @sergioalmela,

For react native we will eventually be adding the hooks and inspector interface.

For the node server SDK you can use hooks. They are our long-term replacement for inspectors and support the use case from this ticket.

https://github.com/launchdarkly/open-sdk-specs/tree/main/specs/HOOK-hooks

In the `afterEvaluation` method you would call the datadog rum method.

**Comment by kinyoklion** [comment]
@lolJS 

The 10.9.0 version of the react-native SDK now includes both hooks and inspectors. I would recommend hooks as the plan is eventually to phase out inspectors.

Thank you,
Ryan
