### ISSUE TITLE
The bug/issue #347 fixed in release @launchdarkly/node-server-sdk v9.0.6 is reappearing in v9.4.7

### ISSUE THREAD

**Issue by TheCreatorGanesh** [launchdarkly/js-core#498]
I was developing node backed server code and using webpack for build. 

Webpack is failing because it is not able find the imports done in js server sdk.

Webpack got succeeded when I downgraded to v9.0.6.

**Comment by kinyoklion** [comment]
Hello @TheCreatorGanesh,

Could you provide an example of the imports it was unable to find?

From this package `@launchdarkly/js-server-sdk-common`?

Or from the node-server

Thank you,
Ryan

**Comment by kinyoklion** [comment]
Also, are you referring to the changes from here: https://github.com/launchdarkly/js-core/pull/346/files

As being what resolved a previous problem for you?

**Comment by TheCreatorGanesh** [comment]
Below are the 2 errors out of 22(All are 'Cannot find modules' issues)

Cannot find module '@launchdarkly/js-sdk-common/src/AttributeReference' or its corresponding type declarations.

Cannot find module '@launchdarkly/js-server-sdk-common/src/LDClientImpl' or its corresponding type declarations.

What I observed is all these are imported from src folders but there is no src folder in the publised lib, these should have been imported from index.d.ts or dist folder(available in the publised lib) atleast.

**Comment by kinyoklion** [comment]
@TheCreatorGanesh Can you share what version of webpack you are using and any configuration?

I've compared the actual packages and dependencies between 9.0.6 and 9.4.7 and all the import locations and import/export types are the same for the references two issues. Which could just mean that webpack is breaking on something earlier.

At least one unrelated type now imports as types, but it is for interfaces and using the older syntax, so it shouldn't break webpack.

**Comment by TheCreatorGanesh** [comment]
@kinyoklion This is strange.

I could replicate issue by pointing to v9.4.7 when you asked for "Could you provide an example of the imports it was unable to find?" and send the error.

Webpack is working now for v9.4.7.

I can remember that line `import BigSegmentStoreStatusProviderImpl from './BigSegmentStatusProviderImpl';`(Working one) was something like `import BigSegmentStoreStatusProviderImpl from './src//BigSegmentStatusProviderImpl';` and throwing error.

![Annotation 2024-07-03 101029](https://github.com/launchdarkly/js-core/assets/30016138/54a70ce2-d35c-4d84-a45b-faa7d1f8b470)

I deleted node_modules and tried again. It is working as expected. I guess we are good to close this issue.

**Comment by kinyoklion** [comment]
@TheCreatorGanesh I am glad it is working now! I was really having a hard time tracking tangible differences in the build output.

The dependencies between the modules are pinned, but this does seem almost like it could have been a mismatch. 

If you encounter future problems let us know.

Thank you,
Ryan
