### ISSUE TITLE
FileDataSourceFactory attempts to load file more than once with incomplete data

### ISSUE THREAD

**Issue by moamen-nour** [launchdarkly/js-core#515]
**Is this a support request?**
No

**Describe the bug**
I am using `FileDataSourceFactory` to read flags data from a file. This file is downloaded on a schedule from a GCS bucket. On v7 this worked as expected. When I migrated to v9, json parsing errors started showing up. After debugging, I noticed the file read in the callback of `fs.watch` can sometimes be incomplete. The callback is fired 3+ times with an incomplete file causing `json.parse` errors, then the last attempt works since it reads the full file. 

I suspect this is due to this function in v7 [maybeReloadForPath](https://github.com/launchdarkly/node-server-sdk/blob/main/file_data_source.js#L119) not being ported to [v9](https://github.com/launchdarkly/js-core/blob/main/packages/sdk/server-node/src/platform/NodeFilesystem.ts#L22).

**To reproduce**
1. Setup `FileDataSourceFactory` with `autoUpdate: true`
2. Upload 1 file with a size close to 79.9 KB (which was my case) to a GCS bucket
3. Run a background code that [downloads the file from GCS](https://github.com/googleapis/nodejs-storage/blob/main/samples/downloadFile.js) to the path provided to `FileDataSourceFactory` constructor
4. Call `allFlagsState` on the sdk

**Expected behavior**
Same behavior as v7. The file is reloaded once with the complete contents. No `json.parse` errors.

**Logs**
```
Unterminated string in JSON at position 41218
Error processing files: SyntaxError: Unterminated string in JSON at position 41218
```

**SDK version**
Was using `launchdarkly-node-server-sdk: ^7.0.1` and switched to `@launchdarkly/node-server-sdk: ^9.4.7`

**Language version, developer tools**
`typescript: ^5.3.3`

**OS/platform**
Platform: `linux/arm64`
Linux Distribution: `Debian`
Docker Image: `node:20`

**Additional context**

**Comment by kinyoklion** [comment]
Hello @moamen-nour,

Thank you for the report. There is an implementation of that same code in the new SDK, but the new implementation logs errors and the old implementation simply suppressed them.

Old:
```
          .catch(() => {});
```
New equivalent:
```
 catch (err) {
          // If this was during start, then the initCallback will be present.
          this.errorHandler?.(err as LDFileDataSourceError);
          this.logger?.error(`Error processing files: ${err}`);
        }
```

The debounce time, which is going to dictate how much it tries to read the file, is the same between both implementations. It only coalesces updates over a 10ms period. If the file is being downloaded directly to, versus downloaded and swapped, then it would not be unexpected for this process to take more than 10ms and then trigger multiple load attempts. The old implementation would have only logged that it reloaded when it was a success.

The behavior here is intentionally different.

Thank you,
Ryan

**Comment by moamen-nour** [comment]
Thanks @kinyoklion

I tried the swap approach and it works with no `js.parse` errors. However, I attempt to download the file before calling sdk's `allFlagsState` function. Since we can't block on `fs.watch` callback we can't guarantee `allFlagsState` will use the currently downloaded file, it might use the old version. Can adding a delay of 10ms after downloading the file and before calling `allFlagsState` function guarantee using the latest file ?

**Comment by moamen-nour** [comment]
Update: I added a 50ms delay after the file download which was sufficient for `allFlagsState` to work on the latest downloaded file

**Comment by kinyoklion** [comment]
@moamen-nour I am going to create a ticket to consider increasing our debounce time. I think probably 100ms is more reasonable than 10.
