### ISSUE TITLE
Jest Mock

### ISSUE THREAD

**Issue by nnrohu** [launchdarkly/js-core#538]
**Is your feature request related to a problem? Please describe.**
Yes, I just switched to this new repository and all my test cases are failing.
**Describe the solution you'd like**
Please provide the mock for new changes.

**Describe alternatives you've considered**
I tried to mock using sample return value but it is failing for ldclient undefined.

**Comment by angelo-hub** [comment]
+1 that would be great, we created a small mock, but the other packages have first class jest support

**Comment by steemcb-phorest** [comment]
For anyone who needs it, we are using this successfully in our jest.setup file with @launchdarkly/react-native-client-sdk `10.9.6`

```
jest.mock('@launchdarkly/react-native-client-sdk', () => ({
  ReactNativeLDClient: jest.fn().mockImplementation(() => {
    return { identify: jest.fn(), close: jest.fn(), allFlags: () => [] }
  }),
  AutoEnvAttributes: {
    Enabled: 1,
    Disabled: 0,
  },
}))
```
