### ISSUE TITLE
Calling require(@launchdarkly/node-server-sdk).init() triggers a never-ending stream of error messages that contain no useful information 

### ISSUE THREAD

**Issue by angolding** [launchdarkly/js-core#559]
**Is this a support request?**
Negative.

**Describe the bug**
Recently I updated a React client-side application to Node 22 and Webpack 5.9x with the latest Webpack-cli and dev-server dependencies.  Now, when I start the application via Webpack Dev Serve, the LaunchDarkly init process kicks off a never-ending stream of error messages:
```
info: [LaunchDarkly] Will retry stream connection in 1000 milliseconds
warn: [LaunchDarkly] Received I/O error ([object Object]) for streaming request - will retry
```
There is no way to increase the retry delay and no way to tell LaunchDarkly to give up after x number of retries.  In addition, it appears that the init process starts spawning multiple retry attempts as the amount of messages logged starts increasing.

Since the log message includes no information about what resource is being connected to using what protocol, and because the err.message parameter is an object that is not deserialized into a string, I have no way of diagnosing the cause of the issue.

FWIW, the `init()` call is made only with our SDK key.

**To reproduce**
I'm guessing that the underlying error is related to an HTTPS proxy but because this bug is about the content of the error messages and how they contain no information to help me debug in any material fashion, I have no way of knowing.

Anyways, 

1. have an app running on a machine using an HTTPS proxy that has issues its own cert.  This may also fail if the streaming server presents a bad HTTPS cert but because there's too much unknown about why my connection is failing, I don't know.
2. in that app, invoke launchDarkly.init() (`launchDarkly` in this case is a const assigned to the result of `require(@launchdarkly/node-server-sdk)`)
3. The streaming processor should fail.  behold the never-end wall of errors

**Expected behavior**

1. first and foremost: streaming retry-on-error behavior MUST BE configurable.  In most cases, I'm not going to need LaunchDarkly running in Webpack Dev Serve so while I am interested in the `init()` call erroring out, I would also appreciate if it did so for 3-5 times, waiting maybe 15 seconds between retries, and then gave up.
2. `I/O error [Object object]` is not a helpful error message.  The SDK may need to introspect the message and either stringify an object, stringify across an array, or just display a string
3. Better logging: when a connection fails, tell me about what the application is trying to connect to using what protocol.  There is no reason to hide this from anybody
5. Make sure not to spawn multiple threads each retrying the same operation in a manner that is permanently increasing.

**Logs**
info: [LaunchDarkly] Will retry stream connection in 1000 milliseconds
warn: [LaunchDarkly] Received I/O error ([object Object]) for streaming request - will retry
...

**SDK version**
`"@launchdarkly/node-server-sdk": "^9.5.2"`

**Language version, developer tools**
Node 20+ (observed in 22.7 and the latest lts/iron (Node 20ish)

**OS/platform**
OS X.  Http/Https going through Zproxy

**Additional context**

**Comment by kinyoklion** [comment]
Hello @angolding,

Thank you for the report. There are a few things to go over before getting to the underlying issue or the log.

> There is no way to increase the retry delay and no way to tell LaunchDarkly to give up after x number of retries. 

The `streamInitialReconnectDelay` controls the initial attempt to connect. There is no way to limit the retries. The streaming connection is used to get the flag configuration and updates from LaunchDarkly, so the SDK will continue to retry indefinitely. It does this using a backoff strategy of exponential with a jitter. So a base of 1,2,4,8,16, so forth. Then it applied up to 50% jitter. So the 5th step could be 8-16 seconds of delay. It stops increasing at 30 seconds of base delay. We never stop trying to reconnect as it is a fundamental part of operation.

If you do not want a streaming connection when running in development, then you can use offline mode if you do not need flag updates in this configuration, or you can use polling which has a configurable interval. 

Next is that you are talking about a react application, but this report is for the node-server-sdk. So I do want to validate that the SDK is only being used in server aspects of this implementation.

In regards to the log, I would like to double check what version of `@launchdarkly/js-sdk-common` you have (from checking your lock file). This message was changed at a specific point and shouldn't be reporting an [object Object] anymore.

The only type of protocol the SDK uses it https unless you specifically configure it to connect to HTTP endpoints, and unfortunately the revised error message doesn't provide better information. This situation arises when the underlying connection closes without any reported reason, just that there is an error and no message associated with it.

It should be `Received I/O error (unknown error)`. We do not stringify unknown JSON objects as the error objects often contain circular references and may contain things like credentials that are not desirable in logs.

The SDK also supports proxy configuration.

```
  /**
   * Allows you to specify configuration for an optional HTTP proxy.
   */
  proxyOptions?: LDProxyOptions;
```

```
export interface LDProxyOptions {
  /**
   * Allows you to specify a host for an optional HTTP proxy.
   */
  host?: string;

  /**
   * Allows you to specify a port for an optional HTTP proxy.
   *
   * Both the host and port must be specified to enable proxy support.
   */
  port?: number;

  /**
   * When using an HTTP proxy, specifies whether it is accessed via `http` or `https`.
   */
  scheme?: string;

  /**
   * Allows you to specify basic authentication parameters for an optional HTTP proxy.
   * Usually of the form `username:password`.
   */
  auth?: string;
}
```

As well as TLS options for things like self-signed certificates.

```
  /**
   * Additional parameters to pass to the Node HTTPS API for secure requests.  These can include any
   * of the TLS-related parameters supported by `https.request()`, such as `ca`, `cert`, and `key`.
   *
   * For more information, see the Node documentation for `https.request()` and `tls.connect()`.
   */
  tlsParams?: LDTLSOptions;
```

```
export interface LDTLSOptions {
  ca?: string | string[] | Buffer | Buffer[];
  cert?: string | string[] | Buffer | Buffer[];
  checkServerIdentity?: (servername: string, cert: any) => Error | undefined;
  ciphers?: string;
  pfx?: string | string[] | Buffer | Buffer[] | object[];
  key?: string | string[] | Buffer | Buffer[] | object[];
  passphrase?: string;
  rejectUnauthorized?: boolean;
  secureProtocol?: string;
  servername?: string;
}
```

Thank you,
Ryan

**Comment by angolding** [comment]
@kinyoklion proxy options solved the source issue, so thanks for that!  I would still advocate for more log information as previously said.

**Comment by kinyoklion** [comment]
@angolding Glad to hear that worked for you. I filed an internal ticket to consider improvements to that log message. 

As you were able to get things working I will be closing this ticket.

Thank you!
Ryan

_Filed internally as 254907_
