### ISSUE TITLE
React native only calculate flag value when use*Variation is called

### ISSUE THREAD

**Issue by SYoder1** [launchdarkly/js-core#588]
**Is your feature request related to a problem? Please describe.**
We are in the process of upgrading from `launchdarkly-react-native-client-sdk` 8.0.0 to v10, and ran into an issue with one of our flag that we don't want the user to be placed into a group before we call to get the flag. I see that in the core-js sdk that flags are evaluated before the user sees the flag for the first time. 

> In the client-side JavaScript SDKs, this is always a fast synchronous operation because all of the feature flag values for the current context have already been loaded into memory.

Example:
Of all the user of our app, only 20% of users have access to a specific screen. On the screen, we want to run an experiment for 10% of users. We only want to evaluate the flag based on 20% of the total user base. Not 100%

**Describe the solution you'd like**
We would like to only be able to evaluate a flag the first time we call the `use*Variation` hook and not when the user is identified. This was possible on v8 using the native sdks.

**Describe alternatives you've considered**

**Additional context**
Maybe this works already and I am just unclear on how it works under the hood.

**Comment by kinyoklion** [comment]
Hello @SYoder1,

For all client-side SDKs the flags are always "evaluated" by our back-end and then the client has all the flag values once identify is complete.

When you call the variation method for a flag, that causes the SDK to emit events indicating that the flag has been evaluated.

This worked the same between the two versions and all client-side SDKs.

The flag insights and data for experiments are based on the events emitted when you call a variation method, or `useXVariation`.

Thank you,
Ryan

**Comment by SYoder1** [comment]
That makes sense! So could the flag change (based on the rules) between sessions if the user hasn't seen the flag the first time yet?

**Comment by kinyoklion** [comment]
I am not sure I completely understand the question. Each time you initialize the SDK it gets a new payload of flag values. If you change something in the LaunchDarkly UI, then the SDK will get updates for values that change. So if you added a rule that changes the value for a given context, then the SDK is notified of that change.

If the context doesn't change, and the configuration doesn't change, then the value for a specific context remains the same.

If you are doing a rollout  or experiment the assignment is deterministic based on the context key. So all your keys will bucket randomly in the space, but a specific key will always bucket the same for a given flag. (But not the same from one flag to another as each flag has seeds and salts to produce different results.) 

Documentation on randomization units is available here: https://docs.launchdarkly.com/home/experimentation/randomization/?q=random



Thank you,
Ryan

**Comment by SYoder1** [comment]
I think that answered my question. Appreciate the help!
