### ISSUE TITLE
10.8.0 has a misnamed d.ts export file

### ISSUE THREAD

**Issue by dcjack** [launchdarkly/js-core#629]
**Is this a support request?**
No, but I already alerted support.

**Describe the bug**
Version 10.8.0 is missing a d.ts definition file.  10.7.0 works just fine with Typescript applications.  You might just need to add that extension to ./LDClientTmpl renaming it to ./LDClientTmpl.d.ts

**To reproduce**
Steps to reproduce the behavior.  Try to use 10.8.0 within a typescript application.

**Expected behavior**
Should be able to access the type without patching the package.

**Logs**
If applicable, add any log output related to your problem.

**SDK version**
10.8.0

**Language version, developer tools**

**OS/platform**
Occurs on both windows, linux and macos

**Additional context**

**Comment by kinyoklion** [comment]
Hello @dcjack,

Could you provide your tsconfig?

It is likely this is an issue with our packages related to the type of resolution in the tsconfig. We will have a fix for that issue coming soon.

Thank you,
Ryan

**Comment by kinyoklion** [comment]
@dcjack Additionally I just published a 10.8.1-beta.1. If you can let me know what you experience with that package, then that would be great.

**Comment by dcjack** [comment]
Hey thank you so much for the quick fix!  10.8.1-beta.1. seems to be working.  I should also add my eslintrc.js has `'import/no-extraneous-dependencies': ['error', { devDependencies: true }]`   but here's my tsconfig ```{
  "extends": "@react-native/typescript-config/tsconfig.json",
  "compilerOptions": {
    "allowSyntheticDefaultImports": true,
    "jsx": "react-native",
    "lib": ["dom", "esnext"],
    "module": "nodenext",
    "moduleResolution": "nodenext",
    "noEmit": true,
    "skipLibCheck": true,
    "resolveJsonModule": true,
    "removeComments": true,
    "sourceMap": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true
  },
  "include": [
    "src",
    "./setup-jest.ts",
    "App.tsx",
    "typings",
    "./assets/svgs/*",
    "./assets/ivyIcons/*"
  ],
  "exclude": [
    "**/*.spec.*",
    "ios/*",
    "node_modules",
    "babel.config.js",
    "metro.config.js",
    "jest.config.js"
  ]
}```

**Comment by kinyoklion** [comment]
Thank you for the tsconfig. 

I experience a few other issues with your tsconfig, but was able to sort those. I will try to get those into the next release as well.

**Comment by kinyoklion** [comment]
Fixed in 10.9.0. Please let me know if you encounter any additional issues.

Thank you,
Ryan
