### ISSUE TITLE
LD Stream is multiplying itself

### ISSUE THREAD

**Issue by alewitt2** [launchdarkly/js-core#633]
**Is this a support request?**
This issue tracker is maintained by LaunchDarkly SDK developers and is intended for feedback on the code in this library. If you're not sure whether the problem you are having is specifically related to this library, or to the LaunchDarkly service overall, it may be more appropriate to contact the LaunchDarkly support team; they can help to investigate the problem and will consult the SDK team if necessary. You can submit a support request by going [here](https://support.launchdarkly.com/) and clicking "submit a request", or by emailing support@launchdarkly.com.

Note that issues filed on this issue tracker are publicly accessible. Do not provide any private account information on your issues. If your problem is specific to your account, you should submit a support request as described above.

**Describe the bug**
I am running my node server locally, where the LD client is initialized before anything else. Everything works as expected, but after a while (not a consitent amount of time) i start seeing LD warnings that there was some error, and that it is restarting the stream in 1000ms. Sometimes this happens as expected and i carry on. Other times i will start to see multiple `Opened LaunchDarkly stream connection` in a row after these errors, leading me to believe multiple streams are being opened. Ultimately, if i leave this process running for a few hours, my entire home network start experiencing internet issues because of how many streams have been opened on my laptop.

**To reproduce**
1. start node server
2. doing local dev as usual
3. after 10-30 minutes start seeing lots of streams being opened
4. exit and restart node to clear out the streams

**Expected behavior**
only a single stream should be open at a time.

**Logs**
after a while a start seeing many streams being opened
```
warn: [LaunchDarkly] Received I/O error (Read timeout, received no data in 300000ms, assuming connection is dead) for streaming request - will retry
info: [LaunchDarkly] Will retry stream connection in 1000 milliseconds
warn: [LaunchDarkly] Received I/O error (Read timeout, received no data in 300000ms, assuming connection is dead) for streaming request - will retry
info: [LaunchDarkly] Will retry stream connection in 1000 milliseconds
warn: [LaunchDarkly] Received I/O error (Read timeout, received no data in 300000ms, assuming connection is dead) for streaming request - will retry
info: [LaunchDarkly] Will retry stream connection in 1000 milliseconds
warn: [LaunchDarkly] Received I/O error (Read timeout, received no data in 300000ms, assuming connection is dead) for streaming request - will retry
info: [LaunchDarkly] Will retry stream connection in 1000 milliseconds
warn: [LaunchDarkly] Received I/O error (Read timeout, received no data in 300000ms, assuming connection is dead) for streaming request - will retry
info: [LaunchDarkly] Will retry stream connection in 1000 milliseconds
warn: [LaunchDarkly] Received I/O error (Read timeout, received no data in 300000ms, assuming connection is dead) for streaming request - will retry
info: [LaunchDarkly] Will retry stream connection in 1000 milliseconds
warn: [LaunchDarkly] Received I/O error (Read timeout, received no data in 300000ms, assuming connection is dead) for streaming request - will retry
info: [LaunchDarkly] Will retry stream connection in 1000 milliseconds
warn: [LaunchDarkly] Received I/O error (Read timeout, received no data in 300000ms, assuming connection is dead) for streaming request - will retry
info: [LaunchDarkly] Will retry stream connection in 1000 milliseconds
info: [LaunchDarkly] Opened LaunchDarkly stream connection
info: [LaunchDarkly] Opened LaunchDarkly stream connection
info: [LaunchDarkly] Opened LaunchDarkly stream connection
info: [LaunchDarkly] Opened LaunchDarkly stream connection
info: [LaunchDarkly] Opened LaunchDarkly stream connection
info: [LaunchDarkly] Opened LaunchDarkly stream connection
info: [LaunchDarkly] Opened LaunchDarkly stream connection
info: [LaunchDarkly] Opened LaunchDarkly stream connection
```

**SDK version**
"@launchdarkly/node-server-sdk": "9.2.2",

**Language version, developer tools**
node/v18.17.1

**OS/platform**
MacOS 15.0.1

**Additional context**

**Comment by kinyoklion** [comment]
Hello @alewitt2,

Thank you for the report. We will take a look.

Thank you,
Ryan

**Comment by kinyoklion** [comment]
Hello @alewitt2,

In your package lock can you check what version of `launchdarkly-eventsource` you have?

Thank you,
Ryan

**Comment by kinyoklion** [comment]
Hello @alewitt2,

This should be fixed in 9.4.3 and newer. The event source library, under certain conditions, could emit an error multiple times for a single request, which triggered multiple error messages and multiple reconnect attempts.

I was only able to replicate this under certain conditions using WSL and docker, but your symptoms are the same.

Related fix to the event source library:
https://github.com/launchdarkly/js-eventsource/commit/bcceb359723e30024321cabe7bddd5d2ffa4434b

Thank you,
Ryan

**Comment by kinyoklion** [comment]
Thank you @alewitt2. After trying out the new version please let me know so that I may close this ticket.

**Comment by alewitt2** [comment]
will do.

**Comment by alewitt2** [comment]
i think we can close this. Preliminary tests look good!

```
warn: [LaunchDarkly] Received I/O error (Read timeout, received no data in 300000ms, assuming connection is dead) for streaming request - will retry
info: [LaunchDarkly] Will retry stream connection in 677 milliseconds
info: [LaunchDarkly] Opened LaunchDarkly stream connection
warn: [LaunchDarkly] Received I/O error (Read timeout, received no data in 300000ms, assuming connection is dead) for streaming request - will retry
info: [LaunchDarkly] Will retry stream connection in 918 milliseconds
info: [LaunchDarkly] Opened LaunchDarkly stream connection
warn: [LaunchDarkly] Received I/O error (Read timeout, received no data in 300000ms, assuming connection is dead) for streaming request - will retry
info: [LaunchDarkly] Will retry stream connection in 662 milliseconds
info: [LaunchDarkly] Opened LaunchDarkly stream connection
```
its only opening 1 stream after failures.
thanks again
