### ISSUE TITLE
Typo for basic proxy auth header

### ISSUE THREAD

**Issue by Alex-Cebula** [launchdarkly/js-core#718]
On line 60 of [NodeRequest.ts](https://github.com/launchdarkly/js-core/blob/main/packages/sdk/server-node/src/platform/NodeRequests.ts) it looks like there's one too many '}' characters in the value of the proxy authorization header. I would think this would cause proxies to not work for node users of this package since their credentials have an extra unexpected character.

**Comment by kinyoklion** [comment]
Hello @Alex-Cebula,

Thank you for the report. I will take a look.

_Filed internally as SDK-1017_
